apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}
  labels:
    draft: {{ default "draft-app" .Values.draft }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      annotations:
        buildID: {{ .Values.buildID }}
      labels:
        draft: {{ default "draft-app" .Values.draft }}
        app: {{ template "fullname" . }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.service.internalPort }}
        env:
          - name: "PORT"
            value: "{{ .Values.service.internalPort }}"
          - name: "GIN_MODE"
            value: "{{ .Values.gin.level }}"
          - name: "LOG_LEVEL"
            value: "{{ .Values.log.level }}"
          - name: "LOG_HANDLER"
            value: "{{ .Values.log.handler }}"
        resources:
{{ toYaml .Values.resources | indent 12 }}
