image: gitpod/workspace-full

# List the ports you want to expose and what to do when they are served. See https://www.gitpod.io/docs/43_config_ports/
ports:
- port: 8080
  onOpen: open-browser

# List the start up tasks. You can start them in parallel in multiple terminals. See https://www.gitpod.io/docs/44_config_start_tasks/
tasks:
  - init: echo 'init' # runs during prebuild
    command: go mod download
  - command: go run main.go
    name: Serve
  - openMode: tab-after
    command: until curl -I '\n' --connect-timeout 5 --max-time 10 --retry 5 --retry-delay 0 --retry-connrefused --retry-max-time 40 localhost:8080/api/v1/level ; do echo "retrying.." && sleep 5 ; done